name: Prettier

on: [push, pull_request]

jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: yarn
  prettier:
    runs-on: ubuntu-latest
    needs: install
    steps:
      - run: yarn prettier:check
